src/BettingHistory.Web/Models/RiskViewModel.cs
using System.Collections.Generic;
using BettingHistory.Dto;

namespace BettingHistory.Web.Models
{
	public class RiskViewModel
	{
		public List<UnusualWinning> UnusualSettledWinnings { get; set; }
		public List<UnusualWinning> UnusualUnsettledWinnings { get; set; }
		public List<AverageBetsRisk> AverageBetsRisks { get; set; }
		public List<HighWinningStake> HighWinningStakes { get; set; }
	}
}

src/BettingHistory.Web/Controllers/BetHistoryController.cs
using System.Web.Mvc;
using BettingHistory.Domain;
using BettingHistory.Web.Models;

namespace BettingHistory.Web.Controllers
{
	public class BetHistoryController : Controller
	{
		readonly IBettingHistoryManager _manager = new BettingHistoryManager();
		// GET: BetHistory
		public ActionResult Index()
		{
			var viewModel = new RiskViewModel
			{
				UnusualSettledWinnings = _manager.GetSettledUnusualWinnings(),
				UnusualUnsettledWinnings = _manager.GetUnSettledUnusualWinnings(),
				AverageBetsRisks = _manager.GetAverageBetsRisks(),
				HighWinningStakes = _manager.GetHighWinningStakesFromUnsettled()
			};
			return View(viewModel);
		}
	}
}

src/BettingHistory.Web/Controllers/DefaultController.cs
using System.Web.Mvc;

namespace BettingHistory.Web.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/BettingHistory.Web/Views/BetHistory/Index.cshtml
@model BettingHistory.Web.Models.RiskViewModel
<h3>Settled</h3>
<div class="panel panel-danger">
	<div class="panel-heading">Winnings with unsual rate</div>
	<div class="panel-body">
		<table class="table">
			<thead>
			<tr>
				<th>Customer</th>
				<th>Bets</th>
				<th>Winings</th>
				<th>Percentage</th>
			</tr>
			</thead>
			<tbody>
			@foreach (var unusualWinning in Model.UnusualSettledWinnings)
			{
				<tr>
					<td>@unusualWinning.Customer</td>
					<td>@unusualWinning.NumberOfBet</td>
					<td>@unusualWinning.NumberOfWinnings</td>
					<td>@unusualWinning.Percentage.ToString("F")</td>
				</tr>
			}
			</tbody>
		</table>
	</div>
</div>
<div class="row">
	<h3>Unsettled</h3>
	<div class="col-sm-6 col-md-4">
		<div class="panel panel-danger">
			<div class="panel-heading">Winnings with unsual rate</div>
			<div class="panel-body">
				<table class="table">
					<thead>
					<tr>
						<th>Customer</th>
						<th>Bets</th>
						<th>Winings</th>
						<th>Percentage</th>
					</tr>
					</thead>
					<tbody>
					@foreach (var unusualWinning in Model.UnusualUnsettledWinnings)
					{
						<tr>
							<td>@unusualWinning.Customer</td>
							<td>@unusualWinning.NumberOfBet</td>
							<td>@unusualWinning.NumberOfWinnings</td>
							<td>@unusualWinning.Percentage.ToString("F")</td>
						</tr>
					}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-4">
		<div class="panel panel-danger">
			<div class="panel-heading">$1000.00 or more winings</div>
			<div class="panel-body">
				<table class="table">
					<thead>
					<tr>
						<th>Customer</th>
						<th>Bet</th>
						<th>To Win</th>
					</tr>
					</thead>
					<tbody>
					@foreach (var unusualWinning in Model.HighWinningStakes)
					{
						<tr>
							<td>@unusualWinning.Customer</td>
							<td>@unusualWinning.Stake</td>
							<td>@unusualWinning.ToWin</td>
						</tr>
					}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-4">
		<div class="panel panel-danger">
			<div class="panel-heading">Higher stakes than average</div>
			<div class="panel-body">
				<table class="table">
					<thead>
					<tr>
						<th>Customer</th>
						<th>Bet</th>
						<th>Avg. Bet</th>
						<th>%</th>
					</tr>
					</thead>
					<tbody>
					@foreach (var unusualWinning in Model.AverageBetsRisks)
					{
						<tr>
							<td>@unusualWinning.Customer</td>
							<td>@unusualWinning.CurrentStakes</td>
							<td>@unusualWinning.PreviousStakes</td>
							<td>@unusualWinning.IncreaseStakes.ToString("F")</td>
						</tr>
					}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

src/BettingHistory.Web/Views/Default/Index.cshtml
<!DOCTYPE html>

<html>
<head>
	<title>title</title>
</head>
<body>
<div>
	  
</div>
</body>
</html>

src/BettingHistory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bet History Risk", "Index", "BetHistory", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
	            <ul class="nav navbar-nav">
		            <li><a href="#">Test</a></li>
	            </ul>
            </div>
        </div>
    </div>

<div class="container body-content">
	<div class="container">
		@RenderBody()
	</div>
	
	<hr/>
	<footer>
		<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
	</footer>
</div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

src/BettingHistory.Web/Views/Shared/_ViewLayout.cshtml
@{
    ViewBag.Title = "_ViewLayout";
}

<h2>_ViewLayout</h2>